[package]
name = "my-obfuscator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.17"
rand = { version = "0.8.5", default-features = false, features = ["rand_chacha", "small_rng", "std", "std_rng"] }
tree-sitter = "0.22"
tree-sitter-python = "0.23"


[build-dependencies]
cc="*"
